server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name sy-locker-view.com www.sy-locker-view.com localhost grafana.sy-locker-view.com;

        root /var/www/html;

    
        index index.html index.htm index.nginx-debian.html;

        location / {
            # 쿠버네티스 MetalLB(인그레스) IP로 전달
            proxy_pass http://172.16.0.110/;

            # [핵심] 원본 IP를 전달하는 헤더 3인방
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # 프록시 관련 추가 설정 (안정성)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_cache_bypass $http_upgrade;


            # 타임아웃 방지
            proxy_connect_timeout 90;
            proxy_send_timeout 90;
            proxy_read_timeout 90;

        }
        
        # 3. 관리자 전용 경로 (IP 제한 및 커스텀 403 적용)
        location /admin/ {
            # [핵심] 오늘 확인한 SY님 PC의 실제 IP 허용
            allow 10.0.255.8;
            # 외부 공인 IP 허용
            allow 218.235.89.82;
            # 그 외 모든 IP 차단
            deny all;

            # 차단 시 보여줄 에러 페이지 설정
            error_page 403 /403.html;

            # 실제 관리자 서비스(K8s 인그레스)로 연결
            proxy_pass http://172.16.0.110/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # [추가] 403 에러 발생 시 K8s 웹 서버에서 파일을 가져오는 통로
        location = /403.html {
            proxy_pass http://172.16.0.110/403.html;
            proxy_set_header Host $host;
            internal; # 외부에서 직접 /403.html로 접속하는 것은 막음
        }
}

# HTTPS(443) 요청을 받으면 HTTP(80)로 던져주는 설정
server {
    listen 443;
    server_name sy-locker-view.com grafana.sy-locker-view.com;

    # 301 리다이렉트를 통해 https -> http로 강제 전환
    return 301 http://$host$request_uri;
}