# 1. Nginx 상태 체크 스크립트 정의 (instance 블록 바깥에 위치)
vrrp_script check_nginx {
    # 1. 쉘(-c)을 통해 전체 경로(/usr/bin/pidof)로 실행하도록 강제합니다.
    # 2. 뒤에 > /dev/null 을 붙여 출력 노이즈를 방지합니다.
    script "/bin/sh -c '/usr/bin/pidof nginx > /dev/null 2>&1'"
    interval 2
    weight -20
}

vrrp_instance VI_1 {
    state MASTER          # 여기는 MASTER
    interface ens37       # Host-only 인터페이스 이름 확인
    virtual_router_id 61
    priority 100          # Master는 Slave(90)보다 높게
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1234
    }
    virtual_ipaddress {
        172.16.0.100      # 서비스용 VIP
        172.16.0.200      # 관리용 VIP
    }

    # 2. 위에서 만든 스크립트 적용
    track_script {
        check_nginx
    }

}