# /etc/keepalived/keepalived.conf

# [외부망용 - 서비스 접속용]
vrrp_instance VI_1 {
    state MASTER
    interface ens33        # 본인의 네트워크 인터페이스
    virtual_router_id 51   # 동일 네트워크 내 유일한 값
    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1234
    }
    virtual_ipaddress {
        172.16.0.200       # 사용할 VIP(호스트 PC가 접속할 IP)
    }
}


# [내부망용 - 노드 게이트웨이용]
vrrp_instance VI_INTERNAL {
    state MASTER
    interface ens33          # 내부망 인터페이스 (동일할 경우 ens33 유지)
    virtual_router_id 52     # 외부용(51)과 겹치지 않게 설정
    priority 101
    advert_int 1
    virtual_ipaddress {
        172.16.0.100          # 내부 노드들이 바라볼 게이트웨이 IP
    }
}